const {chromium}=require('C:/Users/MAKRO/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const {openStore,password}=await import('../store.js');const db=openStore(path.resolve('data'));db.prepare('INSERT OR IGNORE INTO tenants VALUES (?,?)').run('preview','VenuePro · Demo local');db.prepare('INSERT OR REPLACE INTO users (email,tenant,password) VALUES (?,?,?)').run('demo@signage.local','preview',password('Signage-demo-local-2026'));db.prepare('DELETE FROM devices WHERE tenant=?').run('preview');db.prepare('DELETE FROM playlists WHERE tenant=?').run('preview');db.prepare('DELETE FROM locations WHERE tenant=?').run('preview');db.close();
 const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto('http://localhost:3080/');await page.locator('#loginForm [name=email]').fill('demo@signage.local');await page.locator('#loginForm [name=password]').fill('Signage-demo-local-2026');await page.locator('#loginForm .primary').click();await page.locator('#shell').waitFor({state:'visible'});
  await page.locator('[data-new-location]').click();await page.locator('#locationForm [name=name]').fill('Pasadena — Bar principal');await page.locator('#locationForm .primary').click();await page.locator('#locationDialog').waitFor({state:'hidden'});await page.locator('[data-location]').filter({hasText:'Pasadena'}).click();
  const playerContext=await browser.newContext({viewport:{width:1280,height:720}}),player=await playerContext.newPage();player.on('pageerror',e=>errors.push(e.message));await player.goto('http://localhost:3080/player.html');await player.locator('#qr').waitFor({state:'visible'});const code=await player.locator('#code').textContent();assert.match(code,/^[A-F0-9]{12}$/);
  await page.locator('[data-action=pair]').first().click();const qrData=await player.locator('#qr').getAttribute('src');const decoded=await page.evaluate(async data=>{const blob=new Blob([Uint8Array.from(atob(data.split(',')[1]),c=>c.charCodeAt(0))],{type:'image/png'});const scanner=new Html5Qrcode('reader');const decoded=await scanner.scanFile(new File([blob],'qr.png',{type:'image/png'}),false);await scanner.clear();return decoded;},qrData);assert.equal(decoded,'venuepro-signage:'+code);await page.locator('#pairCode').fill(decoded.split(':')[1]);await page.locator('#pairForm [name=name]').fill('Recepción · Prueba navegador');await page.locator('#pairForm .primary').click();await page.locator('#pairDialog').waitFor({state:'hidden'});
  await page.locator('[data-view=library]').click();const svg='<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="#b1ed89"/><text x="80" y="280" font-family="Arial" font-size="90" fill="#213b2c">BIENVENIDOS.</text><text x="85" y="365" font-family="Arial" font-size="32" fill="#436637">VenuePro · Tu evento empieza aquí.</text></svg>';
  const art=await context.newPage();await art.setContent(svg);const png=await art.locator('svg').screenshot();await art.close();await page.locator('#upload').setInputFiles({name:'Bienvenida.png',mimeType:'image/png',buffer:png});await page.locator('.card h3').filter({hasText:'Bienvenida.png'}).first().waitFor();
  await page.locator('[data-view=playlists]').click();await page.locator('[data-action=newList]').first().click();await page.locator('#listName').fill('Bienvenida · Recepción');await page.locator('#addItem').click();await page.locator('#playlistForm .primary').click();await page.locator('#playlistDialog').waitFor({state:'hidden'});
  await page.locator('[data-view=screens]').click();await page.locator('[data-action=assign]').last().click();await page.locator('#assignForm .primary').click();await page.locator('#assignDialog').waitFor({state:'hidden'});
  await page.locator('[data-view=schedule]').click();await page.locator('[data-schedule-new]').click();await page.locator('#scheduleForm [name=name]').fill('Bienvenida de la mañana');await page.locator('#scheduleForm .primary').click();await page.locator('#scheduleDialog').waitFor({state:'hidden'});await page.locator('.schedule-card').first().waitFor();
  fs.mkdirSync('output',{recursive:true});for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+width);await page.screenshot({path:`output/schedule-${width}.png`,fullPage:true});}
  await player.waitForFunction(()=>document.querySelector('#stage > img'),null,{timeout:30000});await player.screenshot({path:'output/player-online.png'});
  assert.equal(await player.evaluate(()=>selectItems({items:['fallback'],schedules:[{timezone:'America/Chicago',days:[1],start:'08:00',end:'11:00',fromDate:'',toDate:'',items:['scheduled']}]},new Date('2026-09-14T13:00:00Z'))[0]),'scheduled');
  assert.equal(await player.evaluate(()=>selectItems({items:['fallback'],schedules:[{timezone:'America/Chicago',days:[1],start:'08:00',end:'11:00',fromDate:'',toDate:'',items:['scheduled']}]},new Date('2026-09-14T16:00:00Z'))[0]),'fallback');
  await playerContext.setOffline(true);await player.reload();await player.waitForFunction(()=>document.querySelector('#stage > img'),null,{timeout:10000});assert(await player.locator('#stage > img').evaluate(e=>e.complete&&e.naturalWidth>0));await player.screenshot({path:'output/player-offline.png'});
  await page.locator('[data-view=screens]').click();await page.locator('[data-locations-back]').click();await page.evaluate(()=>load());for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`output/locations-${width}.png`,fullPage:true});}
  await page.locator('[data-all-screens]').click();await page.setViewportSize({width:390,height:900});await page.screenshot({path:'output/screens-390.png',fullPage:true});
  assert.deepEqual(errors,[]);console.log('PASS: actual QR decode, pairing, upload, publication, schedules/timezone boundaries, mobile/desktop layout, offline reload.');await playerContext.close();
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
