const {chromium}=require('C:/Users/MAKRO/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();await page.goto(process.env.TEST_URL||'http://localhost:3082');await page.locator('#loginForm [name=email]').fill('demo@signage.local');await page.locator('#loginForm [name=password]').fill('Signage-demo-local-2026');await page.locator('#loginForm .primary').click();await page.locator('#shell').waitFor({state:'visible'});
 const pair=await page.evaluate(async()=>{const pair=await api('/api/pair/start',{});await api('/api/pair/claim',{code:pair.code,name:'Diagnóstico prueba'});await fetch('/api/player/heartbeat',{method:'POST',headers:{Authorization:'Bearer '+pair.secret,'Content-Type':'application/json'},body:JSON.stringify({error:'Video no compatible <test>',version:''})});await load();return pair;});
 await page.locator('[data-all-screens]').click();const badge=page.locator(`.device-label[data-device-diagnostics="${pair.id}"]`);assert.match(await badge.textContent(),/CON AVISO/);await badge.focus();await page.keyboard.press('Enter');const dialog=page.locator('.device-diagnostic');await dialog.locator('h3').waitFor();assert.equal(await dialog.locator('h3').textContent(),'Diagnóstico prueba');assert.equal(await dialog.locator('.diagnostic-error').textContent(),'Video no compatible <test>');assert.match(await dialog.textContent(),/No registrada por el reproductor/);assert.match(await dialog.textContent(),/no confirma que el problema siga activo/);
 const before=await page.evaluate(async id=>(await api('/api/state')).devices.find(d=>d.id===id).revision,pair.id);await dialog.locator('[data-retry]').click();await page.waitForFunction(()=>document.querySelector('.device-diagnostic [role=status]').textContent.includes('Solicitud registrada'));assert.equal(await page.evaluate(async id=>(await api('/api/state')).devices.find(d=>d.id===id).revision,pair.id),before+1);
 await dialog.locator('.dialog-head button').click();const card=badge.locator('..').locator('..').locator('..');await card.locator('summary').click();await card.locator('.device-more [data-device-diagnostics]').click();await dialog.locator('h3').waitFor();await dialog.locator('.dialog-head button').click();
 // Read-only response keeps diagnostics available while disabling the mutation.
 await page.route('**/api/state',async route=>{const response=await route.fetch(),json=await response.json();json.role='viewer';await route.fulfill({response,json});});await badge.click();await dialog.locator('h3').waitFor();assert(await dialog.locator('[data-retry]').isDisabled());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));console.log('PASS: accessible warning, escaped real error, honest dates, persisted sync command, options entry and read-only controls.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
