const {chromium}=require('C:/Users/MAKRO/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createRequire}=require('node:module');const {PNG}=createRequire(require.resolve('qrcode'))('pngjs');
(async()=>{const {createApp}=await import('../server.js'),{password}=await import('../store.js');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ds-studio-ui-'));const png=new PNG({width:320,height:180});for(let i=0;i<png.data.length;i+=4)png.data.set([24,120,100,255],i);const bytes=PNG.sync.write(png);let paidCalls=0;
 const {app,db}=createApp({DATA_DIR:dir,STORAGE_MODE:'local',PUBLIC_URL:'http://127.0.0.1:3097',AGENCY_SIGNAGE_SECRET:'mock-only-studio-encryption-key-123456'},{request:async(url,options)=>{assert.equal(options.headers.Authorization,'Bearer mock-company-api-key');if(url.includes('/models/'))return new Response(JSON.stringify({id:'gpt-image-2'}));paidCalls++;return new Response(JSON.stringify({data:[{b64_json:bytes.toString('base64')}],usage:{input_tokens:10,output_tokens:20}}));}});
 db.prepare('INSERT INTO tenants VALUES (?,?)').run('studio-ui','Restaurante VenuePro');db.prepare('INSERT INTO users(email,tenant,password,role) VALUES (?,?,?,?)').run('studio@test.local','studio-ui',password('studio-test-password'),'admin');db.prepare('INSERT INTO agency_links(external,tenant,active,kind) VALUES (?,?,1,?)').run('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','studio-ui','crm');
 const server=await new Promise(r=>{const s=app.listen(3097,'127.0.0.1',()=>r(s));}),base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({channel:'chrome',headless:true});
 try{const page=await browser.newPage({viewport:{width:390,height:844}});page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(base);await page.locator('#loginForm [name=email]').fill('studio@test.local');await page.locator('#loginForm [name=password]').fill('studio-test-password');await page.locator('#loginForm .primary').click();await page.locator('[data-view=studio]').waitFor({state:'visible'});await page.locator('[data-view=studio]').click();await page.locator('#studioBrief').waitFor();
 await page.locator('.studio-config summary').click();await page.locator('#studioConfig [name=apiKey]').fill('mock-company-api-key');await page.locator('#studioConfig [name=monthlyLimit]').fill('3');await page.locator('#studioConfig [name=enabled]').check();await page.locator('#studioConfig button').first().click();await page.locator('.studio-config summary').click();await page.locator('[data-studio-verify]').click();await page.waitForFunction(()=>document.querySelector('#studioStatus').textContent.includes('comprobado'));
 await page.locator('#studioBrief [name=name]').fill('Menú del día');await page.locator('#studioBrief [name=kind]').selectOption('menu');await page.locator('#studioBrief [name=orientation]').selectOption('portrait');await page.locator('#studioBrief [name=headline]').fill('Menú del día');await page.locator('#studioBrief [name=price]').fill('$19.95');await page.locator('#studioBrief [name=contact]').fill('555-0101');await page.locator('#studioBrief .primary').click();await page.locator('[data-studio-generate]').waitFor();await page.locator('[data-studio-generate]').click();await page.locator('[data-use-job]').first().waitFor({timeout:15000});assert.equal(paidCalls,1);await page.locator('[data-use-job]').first().click();await page.waitForFunction(()=>document.querySelector('#studioBrief [name=background]').value!=='');await page.locator('[data-layer="1"] textarea').fill('$18.50');await page.locator('#studioBrief .primary').click();
 await page.waitForFunction(()=>!document.querySelector('[data-studio-export]').disabled);await page.locator('[data-studio-export]').click();await page.waitForFunction(()=>document.querySelector('#studioStatus').textContent.includes('Resultado guardado'));const state=await page.evaluate(()=>api('/api/state'));assert.equal(state.assets.length,1);assert.equal(state.devices.length,0);const stored=JSON.parse(db.prepare('SELECT data FROM studio_drafts WHERE tenant=?').get('studio-ui').data);assert.equal(stored.layers[1].text,'$18.50');assert.equal(stored.layers[2].text,'555-0101');assert.equal(paidCalls,1);assert.equal(await page.locator('#studioCanvas').getAttribute('height'),'1920');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+width);}
 fs.mkdirSync('output',{recursive:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'output/studio-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: tenant setup, mocked image proposal, editable price/phone layers, separate export, no screen publication, responsive editor. No paid API call.');
 }finally{await browser.close();await new Promise(r=>server.close(r));db.close();fs.rmSync(dir,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
